-- Privacy-minimized campaign analytics for onesmarter.com/practices.
-- Run this once in Supabase Dashboard -> SQL Editor.

create table if not exists public.practice_campaign_events (
  id bigint generated by default as identity primary key,
  event text not null check (event in (
    'page_view',
    'conversation_started',
    'url_provided',
    'scan_completed',
    'results_viewed',
    'email_captured',
    'report_sent',
    'human_handoff',
    'conversation_depth'
  )),
  source text not null default 'none' check (char_length(source) between 1 and 20),
  session_id text not null check (char_length(session_id) between 1 and 80),
  depth smallint check (depth between 0 and 200),
  path text not null default '/practices',
  occurred_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists practice_campaign_events_occurred_at_idx
  on public.practice_campaign_events (occurred_at desc);

create index if not exists practice_campaign_events_source_event_idx
  on public.practice_campaign_events (source, event, occurred_at desc);

alter table public.practice_campaign_events enable row level security;

-- Browser roles receive no access. Inserts come only from the Vercel
-- server function using a Supabase secret/service-role key.
revoke all on table public.practice_campaign_events from anon, authenticated;
grant insert, select on table public.practice_campaign_events to service_role;
grant usage, select on sequence public.practice_campaign_events_id_seq to service_role;

comment on table public.practice_campaign_events is
  'Privacy-minimized OneSmarter postcard funnel events. No messages, emails, phone numbers, scanned URLs, IP addresses, or transcripts.';
